apiVersion: v1
kind: Pod
metadata:
  name: web-prod
  labels:
    app: web
    environment: production
    tier: frontend
spec:
  containers:
  - name: web-prod
    image: nginx:1.21
---
apiVersion: v1
kind: Pod
metadata:
  name: web-dev
  labels:
    app: web
    environment: development
    tier: frontend
spec:
  containers:
  - name: web-dev
    image: nginx:1.21
---
apiVersion: v1
kind: Pod
metadata:
  name: api-prod
  labels:
    app: api
    environment: production
    tier: backend
spec:
  containers:
  - name: api-prod
    image: nginx:1.21