apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
    - name: app
      image: busybox:1.35
      command: ["sh", "-c", "echo 'Hello from PV!' > /app/data/hello.txt && cat /app/data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: data-volume
          mountPath: /app/data
